name: mvc_bolierplate_getx
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.1.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.4
  get: ^4.6.5
  google_fonts: ^3.0.1
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
