name: mvc_bolierplate_getx
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.1.2
  dio: ^4.0.6
  firebase_analytics: ^9.3.3
  firebase_core: ^1.21.1
  firebase_crashlytics: ^2.8.9
  firebase_messaging: ^13.0.0
  firebase_remote_config: ^2.0.16
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.4
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.1
  internet_connection_checker: ^0.0.1+4
  flutter_login_facebook: ^1.6.0
  intl: ^0.17.0
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
